GET http://localhost:8080/kotlin-msg/v1/messages

###
GET http://localhost:8080/kotlin-msg/v1/messages/32e4a13c-0538-4191-9940-5270df3ebdb2

###
POST http://localhost:8080/kotlin-msg/v1/messages
Content-Type: application/json

{
  "content": "Hello World!"
}

###
PUT http://localhost:8080/kotlin-msg/v1/messages/fe8152e9-225d-49c9-a866-1acb6eafc0a3
Content-Type: application/json

{
"content": "Olá mundo!"
}

###
DELETE http://localhost:8080/kotlin-msg/v1/messages/8b447eba-b034-43ad-9f00-8e663c91d3de

